Add a way to disable sim objects
nasa/trick pull request #1364
Opened 2022-10-10 20:09 UTC by jdeans289

Adds functions that differentiate disabling jobs in a sim object from disabling the sim object itself, along with tests and documentation.

```
// Command to turn on/off the sim_object. If sim object is disabled then enabled, jobs retain their status from before.
int set_sim_object_onoff(std::string sim_object_name, int on) ;

// Command to get sim object on/off status. 1 for on, 0 for off, -1 if object not found.
int get_sim_object_onoff(std::string sim_object_name);

// Command to turn all the individual jobs on/off. Does not set overall sim object status.
int set_sim_object_jobs_onoff(std::string sim_object_name, int on) ;

```

closes #1217

2022-10-10 20:17 UTC, jdeans289 commented on include/trick/SimObject.hh
> +            void enable_all_jobs() ;
Would this change break some existing sims?

2022-10-28 18:35 UTC, ArjunSharda requested changes
Hi! Nice PR. I have a suggestion though, that I made.

2022-10-28 18:35 UTC, ArjunSharda commented on trick_source/sim_services/Executive/test/Makefile
> +	# Filter out information about directories that we don't care about.
```suggestion
	# Remove information about directories that we don't care about.
```

2022-11-11 20:47 UTC, jmpenn approved these changes
Looks like a solid change to me. I like the overall completeness: the testing, the depreciation messages.

2022-11-15 15:16 UTC, merged